### ISSUE TITLE
Problem Building Image

### ISSUE THREAD

**Issue by juandados** [beevelop/docker-java#5]
It is not possible build this image, using the command: docker build -t beevelop/java github.com/beevelop/docker-java
![screenshot from 2019-01-15 23-16-56](https://user-images.githubusercontent.com/20366497/51232528-e4814800-191b-11e9-9e8b-2721d70cf8e3.png)
It seems to be related with the oracle downloading server.

**Comment by beevelop** [comment]
This seems weird. Does this issue still occur? Maybe it was a temporary issue.

**Comment by Phoscur** [comment]
https://github.com/beevelop/docker-java/blob/4a7dd4dd7fa4834541fbb4376acbb9af36eda465/Dockerfile#L16
Issue does still occur! Oracle changed their licensing again.

I just got my fastlane pipeline back up running with a new image [phoscur/docker-ionic](https://github.com/Phoscur/docker-ionic).

@beevelop I like your approach with many small images, but your stack currently only works because you are not rebuilding them..
What's your solution for java8?

**Comment by beevelop** [comment]
Well, that's definitely an issue. The license changes of Oracle Java since April 2019 make it quite hard to use Oracle Java. I guess we need to switch to OpenJDK and hope for the best.

@Phoscur: It's quite a while ago, that I started building up the "image tree". I definitely need to put some effort in, to get them up to date. Help and feedback is highly appreciated. I'll try my best to update them in the next few days.

**Comment by Phoscur** [comment]
Considering the android fastlane build stack, java8 is/was the greatest issue. Have a look at these changes: https://github.com/Phoscur/docker-ionic/commit/e39423cebd576b39ac87ac95a5607c5039879ba3
But the other updates pretty much worked out of the box (in my case debian buster).

**Comment by beevelop** [comment]
@Phoscur: Puh, alright. I'll use it as a basis. Thank you so far.

**Comment by beevelop** [comment]
So switching to OpenJDK should resolve the issue. Feel free to reopen / open another if it happends again. Thank you guys.
